name: coop
BASE_CONFIG: configs/trainers/default.yaml

# Dataset root
root: /mnt/features/VDATA/

# Datasets
datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]
# datasets: [caltech101]

# Seeds and shots
seeds: [1, 2, 3, 4, 5]
shots: [1, 2, 4, 8, 16]

# Output directory template
template: "{experiment}/{dataset}/coop_{shots}shots_{sig}/seed{seed}"

# Grid of hyperparameters
grid:
  {}

TRAINER_NAME: Adapter-CoOp

OPTIM:
  # CoOp defaults
  NAME: sgd
  LR: 0.002
  MAX_EPOCH: 100

TRAINER:
  ADAPTER:
    # CoOp defaults
    N_CTX: 16
    # CTX_INIT: "a photo of a"


