DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.01
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 0.0
  MOMENTUM: 0.9

TRAIN:
  PRINT_FREQ: 5

TRAINER:
  ADAPTER:
    TEMPLATE_INIT_METHOD: uniform
    NUM_TEMPLATES: 8
    L2_LAMBDA: 0.5
    # GP
    GP_KERNEL_TYPE: linear
    GP_NUM_MC_SAMPLES_TRAIN: 30
    GP_NUM_MC_SAMPLES_EVAL: 300
    GP_USE_ELBO: False
    GP_LR: 1.e-3
    GP_BETA: 1
    LEARN_TOKEN_LAMBDA: 8e-3
    GP_PCA_DIM: 256

# Default trainer selection
TRAINER_NAME: Adapter

