name: taskres
BASE_CONFIG: configs/trainers/default.yaml

# Dataset root
root: /mnt/features/VDATA/

# Datasets
datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, ucf101, food101, stanford_cars, eurosat, dtd]
# datasets: [caltech101]

# Seeds and shots
seeds: [1, 2, 3, 4, 5]
shots: [1, 2, 4, 8, 16, 32]

# Output directory template
template: "{experiment}/{dataset}/TaskRes_{shots}shots_{sig}/seed{seed}"

# Grid of hyperparameters
grid:
  {}

TRAINER_NAME: Adapter-TaskRes

TRAINER:
  ADAPTER:
    # TaskRes specific
    TASKRES_RESIDUAL_SCALE: 0.5  # Î± scaling factor (0.5 for most, 1.0 for Flowers102)
    TASKRES_OPTIMIZER: adam
    TASKRES_LR: 0.002
    TASKRES_EPOCHS: 100
    TASKRES_USE_TEMPLATE_WEIGHT_TRAINING: False
    USE_GP: False

