name: benchmarks
BASE_CONFIG: configs/trainers/default.yaml

# Dataset root
root: /mnt/features/VDATA/

# Datasets
datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, ucf101, food101, stanford_cars, eurosat, dtd]
# datasets: [caltech101, oxford_pets, oxford_flowers]

# Seeds and shots
seeds: [1, 2, 3, 4, 5]
shots: [1, 2, 4, 8, 16, 32]

# Output directory template
template: "{experiment}/{dataset}/tip-adapter_{shots}shots_{sig}/seed{seed}"

# Hyperparameters grid
grid:
  TRAINER.ADAPTER.TIP_ADAPTER_TRAINABLE: [True, False]
  TRAINER.ADAPTER.TIP_ADAPTER_USE_TEMPLATE_WEIGHT_TRAINING: [True, False]

TRAINER_NAME: Tip-Adapter

TRAINER:
  ADAPTER:
    # Tip-Adapter defaults
    TIP_ADAPTER_OPTIMIZER: sgd
    TIP_ADAPTER_LR: 0.001
    TIP_ADAPTER_EPOCHS: 20
    TIP_ADAPTER_INIT_ALPHA: 20.0
    TIP_ADAPTER_INIT_BETA: 2.0
    TIP_ADAPTER_EPS: 0.0001


